[package]
name = "bonfida-test-utils"
version = "0.4.0"
authors = ["ellttBen <elliott@bonfida.com>"]
description = "Solana program testing utilities when working with bonfida-utils."
license = "MIT"
edition = "2021"
repository = "https://github.com/Bonfida/bonfida-utils.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.16.16"
solana-program-test = "1.16.16"
solana-sdk = "1.16.16"
spl-token = "3.3.0"
async-trait = "0.1.56"
spl-associated-token-account = "2.2.0"
