[package]
name = "bonfida-utils"
version = "0.1.4"
authors = ["ellttBen <elliott@bonfida.com>"]
description = "Various solana program writing utilities in use by Bonfida."
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
instruction_params_casting = ["bonfida-macros/instruction_params_casting"]

[dependencies]
borsh = "0.9"
solana-program = "1.8"
bonfida-macros = "0.1"
bytemuck = "1.7.2"
