[package]
name = "bonfida-utils"
version = "0.2.3"
authors = ["ellttBen <elliott@bonfida.com>"]
description = "Various solana program writing utilities in use by Bonfida."
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
instruction_params_casting = ["bonfida-macros/instruction_params_casting", "bytemuck"]

[dependencies]
borsh = "0.9"
solana-program = "1.8"
pyth-client = "0.2.2"
bonfida-macros = "0.2.3"
bytemuck = {version = "1.7.2", optional=true}

[dev-dependencies]
solana-client = "1.9"
